name: Publish Release

on:
  push:
    tags:
      - 'v*'

env:
  TAG: ${{ github.ref_name }}

jobs:
  validate-version:
    name: Validate version tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: ci/validate_version.sh ${TAG}

  test:
    name: Test on ${{ matrix.os }}
    needs: validate-version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'
      - run: ci/test.sh

  build:
    name: Build and package ${{ matrix.os }}-${{ matrix.arch }}.${{ matrix.package_format }}
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['edit-cli']
        # os: [linux, windows, darwin]
        os: [linux, darwin]
        arch: [amd64, arm64]
        package_format: [tar.gz, zip]
        exclude:
          - os: windows
            package_format: tar.gz
    env:
      TARGET: ${{ matrix.target }}
      OS: ${{ matrix.os }}
      ARCH: ${{ matrix.arch }}
      PACKAGE_FORMAT: ${{ matrix.package_format }}
      OUTPUT: ${{ matrix.target }}-${{ matrix.os }}-${{ matrix.arch }}.${{ matrix.package_format }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.5'
        run: ci/package.sh ./cmd/${{ TARGET }}
      - name: upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ OUTPUT }}
          path: dist/${{ OUTPUT }}

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          path: dist
      - run: ci/release.sh ${TAG}
